apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: proxy-kong
  name: proxy-kong
  namespace: kong
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: proxy
          env:
            - name: KONG_ADMIN_GUI_PATH
              value: /manager
            - name: KONG_ADMIN_GUI_URL
              value: https://api-admin.hl.ancalagon.black/manager
