---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - "../../base"
  - "ingress.yaml"

patches:
  - path: change-proxy-deployment.yaml
  - path: change-proxy-service-type.yaml
